#!/usr/bin/env Rscript
#This script uses as input the files generated by cufflinks and returns the transcript and gene counts for each experiment
#cuffcompare and cuffdiff must be installed in linux (they come with cufflinks) and set in the PATH

#UNDER CONSTRUCTION

